# A Heat environment file which can be used to enable a
# a Cinder  Dell Storage Center ISCSI backend, configured via puppet
#
# Configures overrides set in cinder-dellsc.yaml
# which is called by ControllerPreConfig-multiple.yaml
#
#These lines are commented out on purpose - calling via pre deploy script 
#resource_registry:
#  OS::TripleO::ControllerExtraConfigPre: ../puppet/extraconfig/pre_deploy/controller/cinder-dellsc.yaml
  
  

parameter_defaults:
  CinderEnableDellScBackend: true
  CinderDellScBackendName: 'tripleo_dellsc'
  CinderDellScSanIp: 'xxx.xxx.xxx.xxx'
  CinderDellScSanLogin: 'Admin'
  CinderDellScSanPassword: 'Dellsvcs1'
  CinderDellScSsn: '62066'
  CinderDellScIscsiIpAddress: 'xxx.xxx.xxx.xxx'
  CinderDellScIscsiPort: '3260'
  CinderDellScApiPort: '3033'
  CinderDellScServerFolder: 'ServerFolderName'
  CinderDellScVolumeFolder: 'VolumeFolderName'
