heat_template_version: 2014-10-16
description: 'Extra Post-Deployment Config, Controller Only'
parameters:
  servers:
    type: json
  input_values:
    type: json


# Note depends_on may be used for serialization if ordering is important
resources:
  ActiveDirectoryControllerConfig:
    type: /home/stack/templates/extraconfig/post_deploy/apply-controller-activedirectory.yaml 
    properties:
        servers: {get_param: [servers,Controller]}
        input_values: {get_param: input_values}


outputs:
  deploy_stdout:
    value:
      list_join:
      - ''
      - - {get_attr: [ActiveDirectoryControllerConfig, deploy_stdout]}
