heat_template_version: 2014-10-16
description: 'Extra Post-Deployment Config, Compute Only'
parameters:
  servers:
    type: json
  input_values:
    type: json

# Note depends_on may be used for serialization if ordering is important
resources:
  MultiPathConfig:
    type: /home/stack/templates/extraconfig/post_deploy/apply-compute-multipath.yaml
    properties:
        servers: {get_param: [servers,Compute]}
        input_values: {get_param: input_values}

  ADCompConfig:
    type: /home/stack/templates/extraconfig/post_deploy/apply-compute-activedirectory.yaml
    properties:
        servers: {get_param: [servers,Compute]}
        input_values: {get_param: input_values}



outputs:
  deploy_stdout:
    value:
      list_join:
      - ''
      - - {get_attr: [MultiPathConfig, deploy_stdout]}
        - {get_attr: [ADCompConfig, deploy_stdout]}
