heat_template_version: 2014-10-16

description: >
  Apply Dell driver changes to cinder config on overcloud systems

parameters:
  servers:
    type: json

resources:
  DellCinderConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: /home/stack/templates/extraconfig/post_deploy/post_deploy-dell_cinder.sh}

  DellCinderDeployment:
    type: OS::Heat::SoftwareDeployments
    properties:
      servers: {get_param: servers}
      config:  {get_resource: DellCinderConfig}
      actions: ['CREATE','UPDATE'] # do this on CREATE and UPDATE
