heat_template_version: 2014-10-16

description: >
  Apply multipath config to overcloud systems

parameters:
  servers:
    type: json
  input_values:
    type: json

resources:
  MultiPathConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: /home/stack/templates/extraconfig/post_deploy/post_deploy_compute-multipath.sh}

  MultiPathDeployment:
    type: OS::Heat::SoftwareDeployments
    properties:
      name: MultiPathDeployment
      #servers: {get_param: [servers,Compute]}
      servers: {get_param: [servers]}
      config:  {get_resource: MultiPathConfig}
      actions: ['CREATE','UPDATE'] # do this on CREATE and UPDATE
      input_values: {get_param: input_values}
