heat_template_version: 2014-10-16

description: >
  This will be used to modify disk partitions, make opensacap chanes and sriov config changes.

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_file: /home/stack/templates/firstboot/disk_config-openscap.sh}
      - config: {get_resource: reboot_svr}

  reboot_svr:
    type: OS::Heat::SoftwareConfig
    properties:
      config: |
        #!/bin/bash
        shutdown -r 0 

outputs:
  # This means get_resource from the parent template will get the userdata, see:
  # http://docs.openstack.org/developer/heat/template_guide/composition.html#making-your-template-resource-more-transparent
  # Note this is new-for-kilo, an alternative is returning a value then using
  # get_attr in the parent template instead.
  OS::stack_id:
    value: {get_resource: userdata}

